//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.PlanAlimentarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="PlanAlimentarioWS.PlanAlimentarioService")]
    public interface PlanAlimentarioService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoResponse planAlimentarioAlumno(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoResponse> planAlimentarioAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/recetaPorPresetI" +
            "DRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/recetaPorPresetI" +
            "DResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDResponse recetaPorPresetID(PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/recetaPorPresetI" +
            "DRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/recetaPorPresetI" +
            "DResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDResponse> recetaPorPresetIDAsync(PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/ingredientesPres" +
            "etRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/ingredientesPres" +
            "etResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.ingredientesPresetResponse ingredientesPreset(PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/ingredientesPres" +
            "etRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/ingredientesPres" +
            "etResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.ingredientesPresetResponse> ingredientesPresetAsync(PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoPresetRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoPresetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetResponse planAlimentarioAlumnoPreset(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoPresetRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/planAlimentarioA" +
            "lumnoPresetResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetResponse> planAlimentarioAlumnoPresetAsync(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/presetsPorTipoCR" +
            "equest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/presetsPorTipoCR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCResponse presetsPorTipoC(PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/presetsPorTipoCR" +
            "equest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/presetsPorTipoCR" +
            "esponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCResponse> presetsPorTipoCAsync(PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/eliminarPlanAlim" +
            "AlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/eliminarPlanAlim" +
            "AlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoResponse eliminarPlanAlimAlumno(PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/eliminarPlanAlim" +
            "AlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/eliminarPlanAlim" +
            "AlumnoResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoResponse> eliminarPlanAlimAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarIngredien" +
            "tesCompraRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarIngredien" +
            "tesCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraResponse generarIngredientesCompra(PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarIngredien" +
            "tesCompraRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarIngredien" +
            "tesCompraResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraResponse> generarIngredientesCompraAsync(PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/modificarPlanAlu" +
            "mnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/modificarPlanAlu" +
            "mnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoResponse modificarPlanAlumno(PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/modificarPlanAlu" +
            "mnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/modificarPlanAlu" +
            "mnoResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoResponse> modificarPlanAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarNuevoPlan" +
            "AlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarNuevoPlan" +
            "AlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoResponse generarNuevoPlanAlumno(PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarNuevoPlan" +
            "AlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/generarNuevoPlan" +
            "AlumnoResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoResponse> generarNuevoPlanAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/insertarNuevoPla" +
            "nRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/insertarNuevoPla" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanResponse insertarNuevoPlan(PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/insertarNuevoPla" +
            "nRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/PlanAlimentarioService/insertarNuevoPla" +
            "nResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanResponse> insertarNuevoPlanAsync(PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class planAlimentario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno alumnoField;
        
        private presetReceta comidaField;
        
        private int diaField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int fid_NutricionistaField;
        
        private int tipoComidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
                this.RaisePropertyChanged("alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public presetReceta comida {
            get {
                return this.comidaField;
            }
            set {
                this.comidaField = value;
                this.RaisePropertyChanged("comida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int fid_Nutricionista {
            get {
                return this.fid_NutricionistaField;
            }
            set {
                this.fid_NutricionistaField = value;
                this.RaisePropertyChanged("fid_Nutricionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipoComida {
            get {
                return this.tipoComidaField;
            }
            set {
                this.tipoComidaField = value;
                this.RaisePropertyChanged("tipoComida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class alumno : usuario {
        
        private double creditosAprobadosField;
        
        private especialidad especialidadField;
        
        private int matriculadoField;
        
        private string nombreContactoField;
        
        private string numContactoField;
        
        private string parentezcoContactoField;
        
        private planAlimentario[] planesAlimentariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double creditosAprobados {
            get {
                return this.creditosAprobadosField;
            }
            set {
                this.creditosAprobadosField = value;
                this.RaisePropertyChanged("creditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int matriculado {
            get {
                return this.matriculadoField;
            }
            set {
                this.matriculadoField = value;
                this.RaisePropertyChanged("matriculado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreContacto {
            get {
                return this.nombreContactoField;
            }
            set {
                this.nombreContactoField = value;
                this.RaisePropertyChanged("nombreContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numContacto {
            get {
                return this.numContactoField;
            }
            set {
                this.numContactoField = value;
                this.RaisePropertyChanged("numContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string parentezcoContacto {
            get {
                return this.parentezcoContactoField;
            }
            set {
                this.parentezcoContactoField = value;
                this.RaisePropertyChanged("parentezcoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("planesAlimentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public planAlimentario[] planesAlimentarios {
            get {
                return this.planesAlimentariosField;
            }
            set {
                this.planesAlimentariosField = value;
                this.RaisePropertyChanged("planesAlimentarios");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEspecialidadField;
        
        private facultad facultadField;
        
        private int id_especialidadField;
        
        private string nombreEspecialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEspecialidad {
            get {
                return this.descripcionEspecialidadField;
            }
            set {
                this.descripcionEspecialidadField = value;
                this.RaisePropertyChanged("descripcionEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public facultad facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_especialidad {
            get {
                return this.id_especialidadField;
            }
            set {
                this.id_especialidadField = value;
                this.RaisePropertyChanged("id_especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreEspecialidad {
            get {
                return this.nombreEspecialidadField;
            }
            set {
                this.nombreEspecialidadField = value;
                this.RaisePropertyChanged("nombreEspecialidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class facultad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionFacultadField;
        
        private int id_facultadField;
        
        private string nombreFacultadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionFacultad {
            get {
                return this.descripcionFacultadField;
            }
            set {
                this.descripcionFacultadField = value;
                this.RaisePropertyChanged("descripcionFacultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_facultad {
            get {
                return this.id_facultadField;
            }
            set {
                this.id_facultadField = value;
                this.RaisePropertyChanged("id_facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreFacultad {
            get {
                return this.nombreFacultadField;
            }
            set {
                this.nombreFacultadField = value;
                this.RaisePropertyChanged("nombreFacultad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class ingrediente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool azucarField;
        
        private double cantidadField;
        
        private string detalleField;
        
        private bool estadoField;
        
        private bool grasasSaturadasField;
        
        private bool grasasTransField;
        
        private int idIngredienteField;
        
        private int kcalField;
        
        private string nombreField;
        
        private bool sodioField;
        
        private string unidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool azucar {
            get {
                return this.azucarField;
            }
            set {
                this.azucarField = value;
                this.RaisePropertyChanged("azucar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool grasasSaturadas {
            get {
                return this.grasasSaturadasField;
            }
            set {
                this.grasasSaturadasField = value;
                this.RaisePropertyChanged("grasasSaturadas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool grasasTrans {
            get {
                return this.grasasTransField;
            }
            set {
                this.grasasTransField = value;
                this.RaisePropertyChanged("grasasTrans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idIngrediente {
            get {
                return this.idIngredienteField;
            }
            set {
                this.idIngredienteField = value;
                this.RaisePropertyChanged("idIngrediente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int kcal {
            get {
                return this.kcalField;
            }
            set {
                this.kcalField = value;
                this.RaisePropertyChanged("kcal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool sodio {
            get {
                return this.sodioField;
            }
            set {
                this.sodioField = value;
                this.RaisePropertyChanged("sodio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
                this.RaisePropertyChanged("unidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class receta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private bool estadoField;
        
        private int idRecetaField;
        
        private string indicacionesField;
        
        private string nombreField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idReceta {
            get {
                return this.idRecetaField;
            }
            set {
                this.idRecetaField = value;
                this.RaisePropertyChanged("idReceta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string indicaciones {
            get {
                return this.indicacionesField;
            }
            set {
                this.indicacionesField = value;
                this.RaisePropertyChanged("indicaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class presetReceta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private int idPresetRecetaField;
        
        private double kcalField;
        
        private string nombreField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPresetReceta {
            get {
                return this.idPresetRecetaField;
            }
            set {
                this.idPresetRecetaField = value;
                this.RaisePropertyChanged("idPresetReceta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double kcal {
            get {
                return this.kcalField;
            }
            set {
                this.kcalField = value;
                this.RaisePropertyChanged("kcal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string codigoPUCPField;
        
        private string contrasenaField;
        
        private string emailPUCPField;
        
        private string emailPersonalField;
        
        private int estadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoSrcField;
        
        private int id_usuarioField;
        
        private string nombreCompletoField;
        
        private string nombresField;
        
        private ushort sexoField;
        
        private string telefonoMovilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string emailPUCP {
            get {
                return this.emailPUCPField;
            }
            set {
                this.emailPUCPField = value;
                this.RaisePropertyChanged("emailPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string emailPersonal {
            get {
                return this.emailPersonalField;
            }
            set {
                this.emailPersonalField = value;
                this.RaisePropertyChanged("emailPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] fotoSrc {
            get {
                return this.fotoSrcField;
            }
            set {
                this.fotoSrcField = value;
                this.RaisePropertyChanged("fotoSrc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string telefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
                this.RaisePropertyChanged("telefonoMovil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="planAlimentarioAlumno", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class planAlimentarioAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public planAlimentarioAlumnoRequest() {
        }
        
        public planAlimentarioAlumnoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="planAlimentarioAlumnoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class planAlimentarioAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.planAlimentario[] @return;
        
        public planAlimentarioAlumnoResponse() {
        }
        
        public planAlimentarioAlumnoResponse(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recetaPorPresetID", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class recetaPorPresetIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public recetaPorPresetIDRequest() {
        }
        
        public recetaPorPresetIDRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recetaPorPresetIDResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class recetaPorPresetIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.receta @return;
        
        public recetaPorPresetIDResponse() {
        }
        
        public recetaPorPresetIDResponse(PUCPSaludable.PlanAlimentarioWS.receta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ingredientesPreset", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class ingredientesPresetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public ingredientesPresetRequest() {
        }
        
        public ingredientesPresetRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ingredientesPresetResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class ingredientesPresetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.ingrediente[] @return;
        
        public ingredientesPresetResponse() {
        }
        
        public ingredientesPresetResponse(PUCPSaludable.PlanAlimentarioWS.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="planAlimentarioAlumnoPreset", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class planAlimentarioAlumnoPresetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public planAlimentarioAlumnoPresetRequest() {
        }
        
        public planAlimentarioAlumnoPresetRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="planAlimentarioAlumnoPresetResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class planAlimentarioAlumnoPresetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.presetReceta[] @return;
        
        public planAlimentarioAlumnoPresetResponse() {
        }
        
        public planAlimentarioAlumnoPresetResponse(PUCPSaludable.PlanAlimentarioWS.presetReceta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="presetsPorTipoC", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class presetsPorTipoCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipo;
        
        public presetsPorTipoCRequest() {
        }
        
        public presetsPorTipoCRequest(int tipo) {
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="presetsPorTipoCResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class presetsPorTipoCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.presetReceta[] @return;
        
        public presetsPorTipoCResponse() {
        }
        
        public presetsPorTipoCResponse(PUCPSaludable.PlanAlimentarioWS.presetReceta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPlanAlimAlumno", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPlanAlimAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarPlanAlimAlumnoRequest() {
        }
        
        public eliminarPlanAlimAlumnoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPlanAlimAlumnoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPlanAlimAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPlanAlimAlumnoResponse() {
        }
        
        public eliminarPlanAlimAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarIngredientesCompra", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarIngredientesCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public generarIngredientesCompraRequest() {
        }
        
        public generarIngredientesCompraRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarIngredientesCompraResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarIngredientesCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarIngredientesCompraResponse() {
        }
        
        public generarIngredientesCompraResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPlanAlumno", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPlanAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("planesAlimentario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.planAlimentario[] planesAlimentario;
        
        public modificarPlanAlumnoRequest() {
        }
        
        public modificarPlanAlumnoRequest(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] planesAlimentario) {
            this.planesAlimentario = planesAlimentario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPlanAlumnoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPlanAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPlanAlumnoResponse() {
        }
        
        public modificarPlanAlumnoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarNuevoPlanAlumno", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarNuevoPlanAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public generarNuevoPlanAlumnoRequest() {
        }
        
        public generarNuevoPlanAlumnoRequest(int idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarNuevoPlanAlumnoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarNuevoPlanAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.presetReceta[] @return;
        
        public generarNuevoPlanAlumnoResponse() {
        }
        
        public generarNuevoPlanAlumnoResponse(PUCPSaludable.PlanAlimentarioWS.presetReceta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarNuevoPlan", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarNuevoPlanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("plan", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.PlanAlimentarioWS.planAlimentario[] plan;
        
        public insertarNuevoPlanRequest() {
        }
        
        public insertarNuevoPlanRequest(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] plan) {
            this.plan = plan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarNuevoPlanResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarNuevoPlanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarNuevoPlanResponse() {
        }
        
        public insertarNuevoPlanResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlanAlimentarioServiceChannel : PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanAlimentarioServiceClient : System.ServiceModel.ClientBase<PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService>, PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService {
        
        public PlanAlimentarioServiceClient() {
        }
        
        public PlanAlimentarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlanAlimentarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanAlimentarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanAlimentarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.planAlimentarioAlumno(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest request) {
            return base.Channel.planAlimentarioAlumno(request);
        }
        
        public PUCPSaludable.PlanAlimentarioWS.planAlimentario[] planAlimentarioAlumno(int id) {
            PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest();
            inValue.id = id;
            PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).planAlimentarioAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.planAlimentarioAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest request) {
            return base.Channel.planAlimentarioAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoResponse> planAlimentarioAlumnoAsync(int id) {
            PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoRequest();
            inValue.id = id;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).planAlimentarioAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.recetaPorPresetID(PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest request) {
            return base.Channel.recetaPorPresetID(request);
        }
        
        public PUCPSaludable.PlanAlimentarioWS.receta recetaPorPresetID(int id) {
            PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest inValue = new PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest();
            inValue.id = id;
            PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).recetaPorPresetID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.recetaPorPresetIDAsync(PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest request) {
            return base.Channel.recetaPorPresetIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDResponse> recetaPorPresetIDAsync(int id) {
            PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest inValue = new PUCPSaludable.PlanAlimentarioWS.recetaPorPresetIDRequest();
            inValue.id = id;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).recetaPorPresetIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.ingredientesPresetResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.ingredientesPreset(PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest request) {
            return base.Channel.ingredientesPreset(request);
        }
        
        public PUCPSaludable.PlanAlimentarioWS.ingrediente[] ingredientesPreset(int id) {
            PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest inValue = new PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest();
            inValue.id = id;
            PUCPSaludable.PlanAlimentarioWS.ingredientesPresetResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).ingredientesPreset(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.ingredientesPresetResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.ingredientesPresetAsync(PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest request) {
            return base.Channel.ingredientesPresetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.ingredientesPresetResponse> ingredientesPresetAsync(int id) {
            PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest inValue = new PUCPSaludable.PlanAlimentarioWS.ingredientesPresetRequest();
            inValue.id = id;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).ingredientesPresetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.planAlimentarioAlumnoPreset(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest request) {
            return base.Channel.planAlimentarioAlumnoPreset(request);
        }
        
        public PUCPSaludable.PlanAlimentarioWS.presetReceta[] planAlimentarioAlumnoPreset(int id) {
            PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest inValue = new PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest();
            inValue.id = id;
            PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).planAlimentarioAlumnoPreset(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.planAlimentarioAlumnoPresetAsync(PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest request) {
            return base.Channel.planAlimentarioAlumnoPresetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetResponse> planAlimentarioAlumnoPresetAsync(int id) {
            PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest inValue = new PUCPSaludable.PlanAlimentarioWS.planAlimentarioAlumnoPresetRequest();
            inValue.id = id;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).planAlimentarioAlumnoPresetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.presetsPorTipoC(PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest request) {
            return base.Channel.presetsPorTipoC(request);
        }
        
        public PUCPSaludable.PlanAlimentarioWS.presetReceta[] presetsPorTipoC(int tipo) {
            PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest inValue = new PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest();
            inValue.tipo = tipo;
            PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).presetsPorTipoC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.presetsPorTipoCAsync(PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest request) {
            return base.Channel.presetsPorTipoCAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCResponse> presetsPorTipoCAsync(int tipo) {
            PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest inValue = new PUCPSaludable.PlanAlimentarioWS.presetsPorTipoCRequest();
            inValue.tipo = tipo;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).presetsPorTipoCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.eliminarPlanAlimAlumno(PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest request) {
            return base.Channel.eliminarPlanAlimAlumno(request);
        }
        
        public int eliminarPlanAlimAlumno(int id) {
            PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest();
            inValue.id = id;
            PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).eliminarPlanAlimAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.eliminarPlanAlimAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest request) {
            return base.Channel.eliminarPlanAlimAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoResponse> eliminarPlanAlimAlumnoAsync(int id) {
            PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.eliminarPlanAlimAlumnoRequest();
            inValue.id = id;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).eliminarPlanAlimAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.generarIngredientesCompra(PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest request) {
            return base.Channel.generarIngredientesCompra(request);
        }
        
        public byte[] generarIngredientesCompra(int id) {
            PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest inValue = new PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest();
            inValue.id = id;
            PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).generarIngredientesCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.generarIngredientesCompraAsync(PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest request) {
            return base.Channel.generarIngredientesCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraResponse> generarIngredientesCompraAsync(int id) {
            PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest inValue = new PUCPSaludable.PlanAlimentarioWS.generarIngredientesCompraRequest();
            inValue.id = id;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).generarIngredientesCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.modificarPlanAlumno(PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest request) {
            return base.Channel.modificarPlanAlumno(request);
        }
        
        public int modificarPlanAlumno(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] planesAlimentario) {
            PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest();
            inValue.planesAlimentario = planesAlimentario;
            PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).modificarPlanAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.modificarPlanAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest request) {
            return base.Channel.modificarPlanAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoResponse> modificarPlanAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] planesAlimentario) {
            PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.modificarPlanAlumnoRequest();
            inValue.planesAlimentario = planesAlimentario;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).modificarPlanAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.generarNuevoPlanAlumno(PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest request) {
            return base.Channel.generarNuevoPlanAlumno(request);
        }
        
        public PUCPSaludable.PlanAlimentarioWS.presetReceta[] generarNuevoPlanAlumno(int idAlumno) {
            PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest();
            inValue.idAlumno = idAlumno;
            PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).generarNuevoPlanAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.generarNuevoPlanAlumnoAsync(PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest request) {
            return base.Channel.generarNuevoPlanAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoResponse> generarNuevoPlanAlumnoAsync(int idAlumno) {
            PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest inValue = new PUCPSaludable.PlanAlimentarioWS.generarNuevoPlanAlumnoRequest();
            inValue.idAlumno = idAlumno;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).generarNuevoPlanAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanResponse PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.insertarNuevoPlan(PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest request) {
            return base.Channel.insertarNuevoPlan(request);
        }
        
        public int insertarNuevoPlan(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] plan) {
            PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest inValue = new PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest();
            inValue.plan = plan;
            PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanResponse retVal = ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).insertarNuevoPlan(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanResponse> PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService.insertarNuevoPlanAsync(PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest request) {
            return base.Channel.insertarNuevoPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanResponse> insertarNuevoPlanAsync(PUCPSaludable.PlanAlimentarioWS.planAlimentario[] plan) {
            PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest inValue = new PUCPSaludable.PlanAlimentarioWS.insertarNuevoPlanRequest();
            inValue.plan = plan;
            return ((PUCPSaludable.PlanAlimentarioWS.PlanAlimentarioService)(this)).insertarNuevoPlanAsync(inValue);
        }
    }
}
