//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.AlumnoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="AlumnoWS.AlumnoService")]
    public interface AlumnoService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoNombreCodigoR" +
            "equest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoNombreCodigoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoResponse listarAlumnoNombreCodigo(PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoNombreCodigoR" +
            "equest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoNombreCodigoR" +
            "esponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoResponse> listarAlumnoNombreCodigoAsync(PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/modificarAlumnoIDRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/modificarAlumnoIDResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AlumnoWS.modificarAlumnoIDResponse modificarAlumnoID(PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/modificarAlumnoIDRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/modificarAlumnoIDResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.modificarAlumnoIDResponse> modificarAlumnoIDAsync(PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoIDRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AlumnoWS.listarAlumnoIDResponse listarAlumnoID(PUCPSaludable.AlumnoWS.listarAlumnoIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoIDRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoIDResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoIDResponse> listarAlumnoIDAsync(PUCPSaludable.AlumnoWS.listarAlumnoIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/generarPlanAlimenticioReq" +
            "uest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/generarPlanAlimenticioRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AlumnoWS.generarPlanAlimenticioResponse generarPlanAlimenticio(PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/generarPlanAlimenticioReq" +
            "uest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/generarPlanAlimenticioRes" +
            "ponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.generarPlanAlimenticioResponse> generarPlanAlimenticioAsync(PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AlumnoWS.listarAlumnoResponse listarAlumno(PUCPSaludable.AlumnoWS.listarAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AlumnoService/listarAlumnoResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoResponse> listarAlumnoAsync(PUCPSaludable.AlumnoWS.listarAlumnoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class alumno : usuario {
        
        private double creditosAprobadosField;
        
        private especialidad especialidadField;
        
        private int matriculadoField;
        
        private string nombreContactoField;
        
        private string numContactoField;
        
        private string parentezcoContactoField;
        
        private planAlimentario[] planesAlimentariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double creditosAprobados {
            get {
                return this.creditosAprobadosField;
            }
            set {
                this.creditosAprobadosField = value;
                this.RaisePropertyChanged("creditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int matriculado {
            get {
                return this.matriculadoField;
            }
            set {
                this.matriculadoField = value;
                this.RaisePropertyChanged("matriculado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreContacto {
            get {
                return this.nombreContactoField;
            }
            set {
                this.nombreContactoField = value;
                this.RaisePropertyChanged("nombreContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numContacto {
            get {
                return this.numContactoField;
            }
            set {
                this.numContactoField = value;
                this.RaisePropertyChanged("numContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string parentezcoContacto {
            get {
                return this.parentezcoContactoField;
            }
            set {
                this.parentezcoContactoField = value;
                this.RaisePropertyChanged("parentezcoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("planesAlimentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public planAlimentario[] planesAlimentarios {
            get {
                return this.planesAlimentariosField;
            }
            set {
                this.planesAlimentariosField = value;
                this.RaisePropertyChanged("planesAlimentarios");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEspecialidadField;
        
        private facultad facultadField;
        
        private int id_especialidadField;
        
        private string nombreEspecialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEspecialidad {
            get {
                return this.descripcionEspecialidadField;
            }
            set {
                this.descripcionEspecialidadField = value;
                this.RaisePropertyChanged("descripcionEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public facultad facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_especialidad {
            get {
                return this.id_especialidadField;
            }
            set {
                this.id_especialidadField = value;
                this.RaisePropertyChanged("id_especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreEspecialidad {
            get {
                return this.nombreEspecialidadField;
            }
            set {
                this.nombreEspecialidadField = value;
                this.RaisePropertyChanged("nombreEspecialidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class facultad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionFacultadField;
        
        private int id_facultadField;
        
        private string nombreFacultadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionFacultad {
            get {
                return this.descripcionFacultadField;
            }
            set {
                this.descripcionFacultadField = value;
                this.RaisePropertyChanged("descripcionFacultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_facultad {
            get {
                return this.id_facultadField;
            }
            set {
                this.id_facultadField = value;
                this.RaisePropertyChanged("id_facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreFacultad {
            get {
                return this.nombreFacultadField;
            }
            set {
                this.nombreFacultadField = value;
                this.RaisePropertyChanged("nombreFacultad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class presetReceta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private int idPresetRecetaField;
        
        private double kcalField;
        
        private string nombreField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPresetReceta {
            get {
                return this.idPresetRecetaField;
            }
            set {
                this.idPresetRecetaField = value;
                this.RaisePropertyChanged("idPresetReceta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double kcal {
            get {
                return this.kcalField;
            }
            set {
                this.kcalField = value;
                this.RaisePropertyChanged("kcal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class planAlimentario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno alumnoField;
        
        private presetReceta comidaField;
        
        private int diaField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int fid_NutricionistaField;
        
        private int tipoComidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
                this.RaisePropertyChanged("alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public presetReceta comida {
            get {
                return this.comidaField;
            }
            set {
                this.comidaField = value;
                this.RaisePropertyChanged("comida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int fid_Nutricionista {
            get {
                return this.fid_NutricionistaField;
            }
            set {
                this.fid_NutricionistaField = value;
                this.RaisePropertyChanged("fid_Nutricionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipoComida {
            get {
                return this.tipoComidaField;
            }
            set {
                this.tipoComidaField = value;
                this.RaisePropertyChanged("tipoComida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string codigoPUCPField;
        
        private string contrasenaField;
        
        private string emailPUCPField;
        
        private string emailPersonalField;
        
        private int estadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoSrcField;
        
        private int id_usuarioField;
        
        private string nombreCompletoField;
        
        private string nombresField;
        
        private ushort sexoField;
        
        private string telefonoMovilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string emailPUCP {
            get {
                return this.emailPUCPField;
            }
            set {
                this.emailPUCPField = value;
                this.RaisePropertyChanged("emailPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string emailPersonal {
            get {
                return this.emailPersonalField;
            }
            set {
                this.emailPersonalField = value;
                this.RaisePropertyChanged("emailPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] fotoSrc {
            get {
                return this.fotoSrcField;
            }
            set {
                this.fotoSrcField = value;
                this.RaisePropertyChanged("fotoSrc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string telefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
                this.RaisePropertyChanged("telefonoMovil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnoNombreCodigo", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnoNombreCodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarAlumnoNombreCodigoRequest() {
        }
        
        public listarAlumnoNombreCodigoRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnoNombreCodigoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnoNombreCodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AlumnoWS.alumno[] @return;
        
        public listarAlumnoNombreCodigoResponse() {
        }
        
        public listarAlumnoNombreCodigoResponse(PUCPSaludable.AlumnoWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAlumnoID", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAlumnoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AlumnoWS.alumno Alumno;
        
        public modificarAlumnoIDRequest() {
        }
        
        public modificarAlumnoIDRequest(PUCPSaludable.AlumnoWS.alumno Alumno) {
            this.Alumno = Alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAlumnoIDResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarAlumnoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAlumnoIDResponse() {
        }
        
        public modificarAlumnoIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnoID", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarAlumnoIDRequest() {
        }
        
        public listarAlumnoIDRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnoIDResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AlumnoWS.alumno[] @return;
        
        public listarAlumnoIDResponse() {
        }
        
        public listarAlumnoIDResponse(PUCPSaludable.AlumnoWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarPlanAlimenticio", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarPlanAlimenticioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public generarPlanAlimenticioRequest() {
        }
        
        public generarPlanAlimenticioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarPlanAlimenticioResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarPlanAlimenticioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public generarPlanAlimenticioResponse() {
        }
        
        public generarPlanAlimenticioResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumno", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnoRequest {
        
        public listarAlumnoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlumnoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AlumnoWS.alumno[] @return;
        
        public listarAlumnoResponse() {
        }
        
        public listarAlumnoResponse(PUCPSaludable.AlumnoWS.alumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlumnoServiceChannel : PUCPSaludable.AlumnoWS.AlumnoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlumnoServiceClient : System.ServiceModel.ClientBase<PUCPSaludable.AlumnoWS.AlumnoService>, PUCPSaludable.AlumnoWS.AlumnoService {
        
        public AlumnoServiceClient() {
        }
        
        public AlumnoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlumnoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlumnoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoResponse PUCPSaludable.AlumnoWS.AlumnoService.listarAlumnoNombreCodigo(PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest request) {
            return base.Channel.listarAlumnoNombreCodigo(request);
        }
        
        public PUCPSaludable.AlumnoWS.alumno[] listarAlumnoNombreCodigo(string nombre) {
            PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest inValue = new PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest();
            inValue.nombre = nombre;
            PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoResponse retVal = ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).listarAlumnoNombreCodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoResponse> PUCPSaludable.AlumnoWS.AlumnoService.listarAlumnoNombreCodigoAsync(PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest request) {
            return base.Channel.listarAlumnoNombreCodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoResponse> listarAlumnoNombreCodigoAsync(string nombre) {
            PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest inValue = new PUCPSaludable.AlumnoWS.listarAlumnoNombreCodigoRequest();
            inValue.nombre = nombre;
            return ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).listarAlumnoNombreCodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AlumnoWS.modificarAlumnoIDResponse PUCPSaludable.AlumnoWS.AlumnoService.modificarAlumnoID(PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest request) {
            return base.Channel.modificarAlumnoID(request);
        }
        
        public int modificarAlumnoID(PUCPSaludable.AlumnoWS.alumno Alumno) {
            PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest inValue = new PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest();
            inValue.Alumno = Alumno;
            PUCPSaludable.AlumnoWS.modificarAlumnoIDResponse retVal = ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).modificarAlumnoID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.modificarAlumnoIDResponse> PUCPSaludable.AlumnoWS.AlumnoService.modificarAlumnoIDAsync(PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest request) {
            return base.Channel.modificarAlumnoIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.modificarAlumnoIDResponse> modificarAlumnoIDAsync(PUCPSaludable.AlumnoWS.alumno Alumno) {
            PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest inValue = new PUCPSaludable.AlumnoWS.modificarAlumnoIDRequest();
            inValue.Alumno = Alumno;
            return ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).modificarAlumnoIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AlumnoWS.listarAlumnoIDResponse PUCPSaludable.AlumnoWS.AlumnoService.listarAlumnoID(PUCPSaludable.AlumnoWS.listarAlumnoIDRequest request) {
            return base.Channel.listarAlumnoID(request);
        }
        
        public PUCPSaludable.AlumnoWS.alumno[] listarAlumnoID(int id) {
            PUCPSaludable.AlumnoWS.listarAlumnoIDRequest inValue = new PUCPSaludable.AlumnoWS.listarAlumnoIDRequest();
            inValue.id = id;
            PUCPSaludable.AlumnoWS.listarAlumnoIDResponse retVal = ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).listarAlumnoID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoIDResponse> PUCPSaludable.AlumnoWS.AlumnoService.listarAlumnoIDAsync(PUCPSaludable.AlumnoWS.listarAlumnoIDRequest request) {
            return base.Channel.listarAlumnoIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoIDResponse> listarAlumnoIDAsync(int id) {
            PUCPSaludable.AlumnoWS.listarAlumnoIDRequest inValue = new PUCPSaludable.AlumnoWS.listarAlumnoIDRequest();
            inValue.id = id;
            return ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).listarAlumnoIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AlumnoWS.generarPlanAlimenticioResponse PUCPSaludable.AlumnoWS.AlumnoService.generarPlanAlimenticio(PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest request) {
            return base.Channel.generarPlanAlimenticio(request);
        }
        
        public byte[] generarPlanAlimenticio(int id) {
            PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest inValue = new PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest();
            inValue.id = id;
            PUCPSaludable.AlumnoWS.generarPlanAlimenticioResponse retVal = ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).generarPlanAlimenticio(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.generarPlanAlimenticioResponse> PUCPSaludable.AlumnoWS.AlumnoService.generarPlanAlimenticioAsync(PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest request) {
            return base.Channel.generarPlanAlimenticioAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.generarPlanAlimenticioResponse> generarPlanAlimenticioAsync(int id) {
            PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest inValue = new PUCPSaludable.AlumnoWS.generarPlanAlimenticioRequest();
            inValue.id = id;
            return ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).generarPlanAlimenticioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AlumnoWS.listarAlumnoResponse PUCPSaludable.AlumnoWS.AlumnoService.listarAlumno(PUCPSaludable.AlumnoWS.listarAlumnoRequest request) {
            return base.Channel.listarAlumno(request);
        }
        
        public PUCPSaludable.AlumnoWS.alumno[] listarAlumno() {
            PUCPSaludable.AlumnoWS.listarAlumnoRequest inValue = new PUCPSaludable.AlumnoWS.listarAlumnoRequest();
            PUCPSaludable.AlumnoWS.listarAlumnoResponse retVal = ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).listarAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoResponse> PUCPSaludable.AlumnoWS.AlumnoService.listarAlumnoAsync(PUCPSaludable.AlumnoWS.listarAlumnoRequest request) {
            return base.Channel.listarAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AlumnoWS.listarAlumnoResponse> listarAlumnoAsync() {
            PUCPSaludable.AlumnoWS.listarAlumnoRequest inValue = new PUCPSaludable.AlumnoWS.listarAlumnoRequest();
            return ((PUCPSaludable.AlumnoWS.AlumnoService)(this)).listarAlumnoAsync(inValue);
        }
    }
}
