//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.AdministradorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="AdministradorWS.AdministradorService")]
    public interface AdministradorService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRulesRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRulesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.getRulesResponse getRules(PUCPSaludable.AdministradorWS.getRulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRulesRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRulesResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getRulesResponse> getRulesAsync(PUCPSaludable.AdministradorWS.getRulesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRolesRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRolesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.getRolesResponse getRoles(PUCPSaludable.AdministradorWS.getRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRolesRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getRolesResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getRolesResponse> getRolesAsync(PUCPSaludable.AdministradorWS.getRolesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRoleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRoleResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.deleteRoleResponse deleteRole(PUCPSaludable.AdministradorWS.deleteRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRoleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRoleResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.deleteRoleResponse> deleteRoleAsync(PUCPSaludable.AdministradorWS.deleteRoleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRuleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRuleResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.modifyRuleResponse modifyRule(PUCPSaludable.AdministradorWS.modifyRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRuleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRuleResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.modifyRuleResponse> modifyRuleAsync(PUCPSaludable.AdministradorWS.modifyRuleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRoleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRoleResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.modifyRoleResponse modifyRole(PUCPSaludable.AdministradorWS.modifyRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRoleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/modifyRoleResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.modifyRoleResponse> modifyRoleAsync(PUCPSaludable.AdministradorWS.modifyRoleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRuleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRuleResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.deleteRuleResponse deleteRule(PUCPSaludable.AdministradorWS.deleteRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRuleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/deleteRuleResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.deleteRuleResponse> deleteRuleAsync(PUCPSaludable.AdministradorWS.deleteRuleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRoleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRoleResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.insertRoleResponse insertRole(PUCPSaludable.AdministradorWS.insertRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRoleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRoleResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.insertRoleResponse> insertRoleAsync(PUCPSaludable.AdministradorWS.insertRoleRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRuleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRuleResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.insertRuleResponse insertRule(PUCPSaludable.AdministradorWS.insertRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRuleRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/insertRuleResponse" +
            "")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.insertRuleResponse> insertRuleAsync(PUCPSaludable.AdministradorWS.insertRuleRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/noWebServiceReques" +
            "t", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/noWebServiceRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PUCPSaludable.AdministradorWS.noWebServiceResponse noWebService(PUCPSaludable.AdministradorWS.noWebServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/noWebServiceReques" +
            "t", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/noWebServiceRespon" +
            "se")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.noWebServiceResponse> noWebServiceAsync(PUCPSaludable.AdministradorWS.noWebServiceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/changeUserStatusRe" +
            "quest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/changeUserStatusRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.changeUserStatusResponse changeUserStatus(PUCPSaludable.AdministradorWS.changeUserStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/changeUserStatusRe" +
            "quest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/changeUserStatusRe" +
            "sponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.changeUserStatusResponse> changeUserStatusAsync(PUCPSaludable.AdministradorWS.changeUserStatusRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getUsersByStatusRe" +
            "quest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getUsersByStatusRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.AdministradorWS.getUsersByStatusResponse getUsersByStatus(PUCPSaludable.AdministradorWS.getUsersByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getUsersByStatusRe" +
            "quest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/AdministradorService/getUsersByStatusRe" +
            "sponse")]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getUsersByStatusResponse> getUsersByStatusAsync(PUCPSaludable.AdministradorWS.getUsersByStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class regla : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int claveField;
        
        private bool estadoField;
        
        private int id_reglaField;
        
        private string nombreField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_regla {
            get {
                return this.id_reglaField;
            }
            set {
                this.id_reglaField = value;
                this.RaisePropertyChanged("id_regla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class presetReceta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private int idPresetRecetaField;
        
        private double kcalField;
        
        private string nombreField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPresetReceta {
            get {
                return this.idPresetRecetaField;
            }
            set {
                this.idPresetRecetaField = value;
                this.RaisePropertyChanged("idPresetReceta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double kcal {
            get {
                return this.kcalField;
            }
            set {
                this.kcalField = value;
                this.RaisePropertyChanged("kcal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class planAlimentario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private alumno alumnoField;
        
        private presetReceta comidaField;
        
        private int diaField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int fid_NutricionistaField;
        
        private int tipoComidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public alumno alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
                this.RaisePropertyChanged("alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public presetReceta comida {
            get {
                return this.comidaField;
            }
            set {
                this.comidaField = value;
                this.RaisePropertyChanged("comida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int fid_Nutricionista {
            get {
                return this.fid_NutricionistaField;
            }
            set {
                this.fid_NutricionistaField = value;
                this.RaisePropertyChanged("fid_Nutricionista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipoComida {
            get {
                return this.tipoComidaField;
            }
            set {
                this.tipoComidaField = value;
                this.RaisePropertyChanged("tipoComida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class alumno : usuario {
        
        private double creditosAprobadosField;
        
        private especialidad especialidadField;
        
        private int matriculadoField;
        
        private string nombreContactoField;
        
        private string numContactoField;
        
        private string parentezcoContactoField;
        
        private planAlimentario[] planesAlimentariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double creditosAprobados {
            get {
                return this.creditosAprobadosField;
            }
            set {
                this.creditosAprobadosField = value;
                this.RaisePropertyChanged("creditosAprobados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int matriculado {
            get {
                return this.matriculadoField;
            }
            set {
                this.matriculadoField = value;
                this.RaisePropertyChanged("matriculado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreContacto {
            get {
                return this.nombreContactoField;
            }
            set {
                this.nombreContactoField = value;
                this.RaisePropertyChanged("nombreContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numContacto {
            get {
                return this.numContactoField;
            }
            set {
                this.numContactoField = value;
                this.RaisePropertyChanged("numContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string parentezcoContacto {
            get {
                return this.parentezcoContactoField;
            }
            set {
                this.parentezcoContactoField = value;
                this.RaisePropertyChanged("parentezcoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("planesAlimentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public planAlimentario[] planesAlimentarios {
            get {
                return this.planesAlimentariosField;
            }
            set {
                this.planesAlimentariosField = value;
                this.RaisePropertyChanged("planesAlimentarios");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionEspecialidadField;
        
        private facultad facultadField;
        
        private int id_especialidadField;
        
        private string nombreEspecialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionEspecialidad {
            get {
                return this.descripcionEspecialidadField;
            }
            set {
                this.descripcionEspecialidadField = value;
                this.RaisePropertyChanged("descripcionEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public facultad facultad {
            get {
                return this.facultadField;
            }
            set {
                this.facultadField = value;
                this.RaisePropertyChanged("facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_especialidad {
            get {
                return this.id_especialidadField;
            }
            set {
                this.id_especialidadField = value;
                this.RaisePropertyChanged("id_especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreEspecialidad {
            get {
                return this.nombreEspecialidadField;
            }
            set {
                this.nombreEspecialidadField = value;
                this.RaisePropertyChanged("nombreEspecialidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class facultad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionFacultadField;
        
        private int id_facultadField;
        
        private string nombreFacultadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionFacultad {
            get {
                return this.descripcionFacultadField;
            }
            set {
                this.descripcionFacultadField = value;
                this.RaisePropertyChanged("descripcionFacultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_facultad {
            get {
                return this.id_facultadField;
            }
            set {
                this.id_facultadField = value;
                this.RaisePropertyChanged("id_facultad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreFacultad {
            get {
                return this.nombreFacultadField;
            }
            set {
                this.nombreFacultadField = value;
                this.RaisePropertyChanged("nombreFacultad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(especialista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(especialistaSalud))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(nutricionista))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(alumno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private string codigoPUCPField;
        
        private string contrasenaField;
        
        private string emailPUCPField;
        
        private string emailPersonalField;
        
        private int estadoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoSrcField;
        
        private int id_usuarioField;
        
        private string nombreCompletoField;
        
        private string nombresField;
        
        private ushort sexoField;
        
        private string telefonoMovilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string emailPUCP {
            get {
                return this.emailPUCPField;
            }
            set {
                this.emailPUCPField = value;
                this.RaisePropertyChanged("emailPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string emailPersonal {
            get {
                return this.emailPersonalField;
            }
            set {
                this.emailPersonalField = value;
                this.RaisePropertyChanged("emailPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] fotoSrc {
            get {
                return this.fotoSrcField;
            }
            set {
                this.fotoSrcField = value;
                this.RaisePropertyChanged("fotoSrc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string telefonoMovil {
            get {
                return this.telefonoMovilField;
            }
            set {
                this.telefonoMovilField = value;
                this.RaisePropertyChanged("telefonoMovil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(especialistaSalud))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(nutricionista))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public abstract partial class especialista : usuario {
        
        private string biografiaField;
        
        private string direccionLaboralField;
        
        private string telefonoLaboralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string biografia {
            get {
                return this.biografiaField;
            }
            set {
                this.biografiaField = value;
                this.RaisePropertyChanged("biografia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccionLaboral {
            get {
                return this.direccionLaboralField;
            }
            set {
                this.direccionLaboralField = value;
                this.RaisePropertyChanged("direccionLaboral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string telefonoLaboral {
            get {
                return this.telefonoLaboralField;
            }
            set {
                this.telefonoLaboralField = value;
                this.RaisePropertyChanged("telefonoLaboral");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(nutricionista))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public abstract partial class especialistaSalud : especialista {
        
        private string colegiaturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string colegiatura {
            get {
                return this.colegiaturaField;
            }
            set {
                this.colegiaturaField = value;
                this.RaisePropertyChanged("colegiatura");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class nutricionista : especialistaSalud {
        
        private planAlimentario[] planesAlimentariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("planesAlimentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public planAlimentario[] planesAlimentarios {
            get {
                return this.planesAlimentariosField;
            }
            set {
                this.planesAlimentariosField = value;
                this.RaisePropertyChanged("planesAlimentarios");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private int id_rolField;
        
        private string nombreField;
        
        private regla[] reglasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_rol {
            get {
                return this.id_rolField;
            }
            set {
                this.id_rolField = value;
                this.RaisePropertyChanged("id_rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reglas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public regla[] reglas {
            get {
                return this.reglasField;
            }
            set {
                this.reglasField = value;
                this.RaisePropertyChanged("reglas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRules", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class getRulesRequest {
        
        public getRulesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRulesResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class getRulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.regla[] @return;
        
        public getRulesResponse() {
        }
        
        public getRulesResponse(PUCPSaludable.AdministradorWS.regla[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoles", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class getRolesRequest {
        
        public getRolesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRolesResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class getRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.rol[] @return;
        
        public getRolesResponse() {
        }
        
        public getRolesResponse(PUCPSaludable.AdministradorWS.rol[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRole", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class deleteRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int role;
        
        public deleteRoleRequest() {
        }
        
        public deleteRoleRequest(int role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRoleResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class deleteRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public deleteRoleResponse() {
        }
        
        public deleteRoleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyRule", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modifyRuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.regla rule;
        
        public modifyRuleRequest() {
        }
        
        public modifyRuleRequest(PUCPSaludable.AdministradorWS.regla rule) {
            this.rule = rule;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyRuleResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modifyRuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modifyRuleResponse() {
        }
        
        public modifyRuleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyRole", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modifyRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.rol role;
        
        public modifyRoleRequest() {
        }
        
        public modifyRoleRequest(PUCPSaludable.AdministradorWS.rol role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyRoleResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modifyRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modifyRoleResponse() {
        }
        
        public modifyRoleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRule", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class deleteRuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rule;
        
        public deleteRuleRequest() {
        }
        
        public deleteRuleRequest(int rule) {
            this.rule = rule;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteRuleResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class deleteRuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public deleteRuleResponse() {
        }
        
        public deleteRuleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertRole", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.rol role;
        
        public insertRoleRequest() {
        }
        
        public insertRoleRequest(PUCPSaludable.AdministradorWS.rol role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertRoleResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertRoleResponse() {
        }
        
        public insertRoleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertRule", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertRuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.regla rule;
        
        public insertRuleRequest() {
        }
        
        public insertRuleRequest(PUCPSaludable.AdministradorWS.regla rule) {
            this.rule = rule;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertRuleResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertRuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertRuleResponse() {
        }
        
        public insertRuleResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="noWebService", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class noWebServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.alumno arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.nutricionista arg1;
        
        public noWebServiceRequest() {
        }
        
        public noWebServiceRequest(PUCPSaludable.AdministradorWS.alumno arg0, PUCPSaludable.AdministradorWS.nutricionista arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="noWebServiceResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class noWebServiceResponse {
        
        public noWebServiceResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changeUserStatus", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class changeUserStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        public changeUserStatusRequest() {
        }
        
        public changeUserStatusRequest(int id, int status) {
            this.id = id;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changeUserStatusResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class changeUserStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public changeUserStatusResponse() {
        }
        
        public changeUserStatusResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersByStatus", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class getUsersByStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        public getUsersByStatusRequest() {
        }
        
        public getUsersByStatusRequest(string name, int status) {
            this.name = name;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersByStatusResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class getUsersByStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.AdministradorWS.usuario[] @return;
        
        public getUsersByStatusResponse() {
        }
        
        public getUsersByStatusResponse(PUCPSaludable.AdministradorWS.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministradorServiceChannel : PUCPSaludable.AdministradorWS.AdministradorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorServiceClient : System.ServiceModel.ClientBase<PUCPSaludable.AdministradorWS.AdministradorService>, PUCPSaludable.AdministradorWS.AdministradorService {
        
        public AdministradorServiceClient() {
        }
        
        public AdministradorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.getRulesResponse PUCPSaludable.AdministradorWS.AdministradorService.getRules(PUCPSaludable.AdministradorWS.getRulesRequest request) {
            return base.Channel.getRules(request);
        }
        
        public PUCPSaludable.AdministradorWS.regla[] getRules() {
            PUCPSaludable.AdministradorWS.getRulesRequest inValue = new PUCPSaludable.AdministradorWS.getRulesRequest();
            PUCPSaludable.AdministradorWS.getRulesResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).getRules(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getRulesResponse> PUCPSaludable.AdministradorWS.AdministradorService.getRulesAsync(PUCPSaludable.AdministradorWS.getRulesRequest request) {
            return base.Channel.getRulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getRulesResponse> getRulesAsync() {
            PUCPSaludable.AdministradorWS.getRulesRequest inValue = new PUCPSaludable.AdministradorWS.getRulesRequest();
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).getRulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.getRolesResponse PUCPSaludable.AdministradorWS.AdministradorService.getRoles(PUCPSaludable.AdministradorWS.getRolesRequest request) {
            return base.Channel.getRoles(request);
        }
        
        public PUCPSaludable.AdministradorWS.rol[] getRoles() {
            PUCPSaludable.AdministradorWS.getRolesRequest inValue = new PUCPSaludable.AdministradorWS.getRolesRequest();
            PUCPSaludable.AdministradorWS.getRolesResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).getRoles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getRolesResponse> PUCPSaludable.AdministradorWS.AdministradorService.getRolesAsync(PUCPSaludable.AdministradorWS.getRolesRequest request) {
            return base.Channel.getRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getRolesResponse> getRolesAsync() {
            PUCPSaludable.AdministradorWS.getRolesRequest inValue = new PUCPSaludable.AdministradorWS.getRolesRequest();
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).getRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.deleteRoleResponse PUCPSaludable.AdministradorWS.AdministradorService.deleteRole(PUCPSaludable.AdministradorWS.deleteRoleRequest request) {
            return base.Channel.deleteRole(request);
        }
        
        public int deleteRole(int role) {
            PUCPSaludable.AdministradorWS.deleteRoleRequest inValue = new PUCPSaludable.AdministradorWS.deleteRoleRequest();
            inValue.role = role;
            PUCPSaludable.AdministradorWS.deleteRoleResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).deleteRole(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.deleteRoleResponse> PUCPSaludable.AdministradorWS.AdministradorService.deleteRoleAsync(PUCPSaludable.AdministradorWS.deleteRoleRequest request) {
            return base.Channel.deleteRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.deleteRoleResponse> deleteRoleAsync(int role) {
            PUCPSaludable.AdministradorWS.deleteRoleRequest inValue = new PUCPSaludable.AdministradorWS.deleteRoleRequest();
            inValue.role = role;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).deleteRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.modifyRuleResponse PUCPSaludable.AdministradorWS.AdministradorService.modifyRule(PUCPSaludable.AdministradorWS.modifyRuleRequest request) {
            return base.Channel.modifyRule(request);
        }
        
        public int modifyRule(PUCPSaludable.AdministradorWS.regla rule) {
            PUCPSaludable.AdministradorWS.modifyRuleRequest inValue = new PUCPSaludable.AdministradorWS.modifyRuleRequest();
            inValue.rule = rule;
            PUCPSaludable.AdministradorWS.modifyRuleResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).modifyRule(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.modifyRuleResponse> PUCPSaludable.AdministradorWS.AdministradorService.modifyRuleAsync(PUCPSaludable.AdministradorWS.modifyRuleRequest request) {
            return base.Channel.modifyRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.modifyRuleResponse> modifyRuleAsync(PUCPSaludable.AdministradorWS.regla rule) {
            PUCPSaludable.AdministradorWS.modifyRuleRequest inValue = new PUCPSaludable.AdministradorWS.modifyRuleRequest();
            inValue.rule = rule;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).modifyRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.modifyRoleResponse PUCPSaludable.AdministradorWS.AdministradorService.modifyRole(PUCPSaludable.AdministradorWS.modifyRoleRequest request) {
            return base.Channel.modifyRole(request);
        }
        
        public int modifyRole(PUCPSaludable.AdministradorWS.rol role) {
            PUCPSaludable.AdministradorWS.modifyRoleRequest inValue = new PUCPSaludable.AdministradorWS.modifyRoleRequest();
            inValue.role = role;
            PUCPSaludable.AdministradorWS.modifyRoleResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).modifyRole(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.modifyRoleResponse> PUCPSaludable.AdministradorWS.AdministradorService.modifyRoleAsync(PUCPSaludable.AdministradorWS.modifyRoleRequest request) {
            return base.Channel.modifyRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.modifyRoleResponse> modifyRoleAsync(PUCPSaludable.AdministradorWS.rol role) {
            PUCPSaludable.AdministradorWS.modifyRoleRequest inValue = new PUCPSaludable.AdministradorWS.modifyRoleRequest();
            inValue.role = role;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).modifyRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.deleteRuleResponse PUCPSaludable.AdministradorWS.AdministradorService.deleteRule(PUCPSaludable.AdministradorWS.deleteRuleRequest request) {
            return base.Channel.deleteRule(request);
        }
        
        public int deleteRule(int rule) {
            PUCPSaludable.AdministradorWS.deleteRuleRequest inValue = new PUCPSaludable.AdministradorWS.deleteRuleRequest();
            inValue.rule = rule;
            PUCPSaludable.AdministradorWS.deleteRuleResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).deleteRule(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.deleteRuleResponse> PUCPSaludable.AdministradorWS.AdministradorService.deleteRuleAsync(PUCPSaludable.AdministradorWS.deleteRuleRequest request) {
            return base.Channel.deleteRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.deleteRuleResponse> deleteRuleAsync(int rule) {
            PUCPSaludable.AdministradorWS.deleteRuleRequest inValue = new PUCPSaludable.AdministradorWS.deleteRuleRequest();
            inValue.rule = rule;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).deleteRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.insertRoleResponse PUCPSaludable.AdministradorWS.AdministradorService.insertRole(PUCPSaludable.AdministradorWS.insertRoleRequest request) {
            return base.Channel.insertRole(request);
        }
        
        public int insertRole(PUCPSaludable.AdministradorWS.rol role) {
            PUCPSaludable.AdministradorWS.insertRoleRequest inValue = new PUCPSaludable.AdministradorWS.insertRoleRequest();
            inValue.role = role;
            PUCPSaludable.AdministradorWS.insertRoleResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).insertRole(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.insertRoleResponse> PUCPSaludable.AdministradorWS.AdministradorService.insertRoleAsync(PUCPSaludable.AdministradorWS.insertRoleRequest request) {
            return base.Channel.insertRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.insertRoleResponse> insertRoleAsync(PUCPSaludable.AdministradorWS.rol role) {
            PUCPSaludable.AdministradorWS.insertRoleRequest inValue = new PUCPSaludable.AdministradorWS.insertRoleRequest();
            inValue.role = role;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).insertRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.insertRuleResponse PUCPSaludable.AdministradorWS.AdministradorService.insertRule(PUCPSaludable.AdministradorWS.insertRuleRequest request) {
            return base.Channel.insertRule(request);
        }
        
        public int insertRule(PUCPSaludable.AdministradorWS.regla rule) {
            PUCPSaludable.AdministradorWS.insertRuleRequest inValue = new PUCPSaludable.AdministradorWS.insertRuleRequest();
            inValue.rule = rule;
            PUCPSaludable.AdministradorWS.insertRuleResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).insertRule(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.insertRuleResponse> PUCPSaludable.AdministradorWS.AdministradorService.insertRuleAsync(PUCPSaludable.AdministradorWS.insertRuleRequest request) {
            return base.Channel.insertRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.insertRuleResponse> insertRuleAsync(PUCPSaludable.AdministradorWS.regla rule) {
            PUCPSaludable.AdministradorWS.insertRuleRequest inValue = new PUCPSaludable.AdministradorWS.insertRuleRequest();
            inValue.rule = rule;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).insertRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.noWebServiceResponse PUCPSaludable.AdministradorWS.AdministradorService.noWebService(PUCPSaludable.AdministradorWS.noWebServiceRequest request) {
            return base.Channel.noWebService(request);
        }
        
        public void noWebService(PUCPSaludable.AdministradorWS.alumno arg0, PUCPSaludable.AdministradorWS.nutricionista arg1) {
            PUCPSaludable.AdministradorWS.noWebServiceRequest inValue = new PUCPSaludable.AdministradorWS.noWebServiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            PUCPSaludable.AdministradorWS.noWebServiceResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).noWebService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.noWebServiceResponse> PUCPSaludable.AdministradorWS.AdministradorService.noWebServiceAsync(PUCPSaludable.AdministradorWS.noWebServiceRequest request) {
            return base.Channel.noWebServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.noWebServiceResponse> noWebServiceAsync(PUCPSaludable.AdministradorWS.alumno arg0, PUCPSaludable.AdministradorWS.nutricionista arg1) {
            PUCPSaludable.AdministradorWS.noWebServiceRequest inValue = new PUCPSaludable.AdministradorWS.noWebServiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).noWebServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.changeUserStatusResponse PUCPSaludable.AdministradorWS.AdministradorService.changeUserStatus(PUCPSaludable.AdministradorWS.changeUserStatusRequest request) {
            return base.Channel.changeUserStatus(request);
        }
        
        public int changeUserStatus(int id, int status) {
            PUCPSaludable.AdministradorWS.changeUserStatusRequest inValue = new PUCPSaludable.AdministradorWS.changeUserStatusRequest();
            inValue.id = id;
            inValue.status = status;
            PUCPSaludable.AdministradorWS.changeUserStatusResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).changeUserStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.changeUserStatusResponse> PUCPSaludable.AdministradorWS.AdministradorService.changeUserStatusAsync(PUCPSaludable.AdministradorWS.changeUserStatusRequest request) {
            return base.Channel.changeUserStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.changeUserStatusResponse> changeUserStatusAsync(int id, int status) {
            PUCPSaludable.AdministradorWS.changeUserStatusRequest inValue = new PUCPSaludable.AdministradorWS.changeUserStatusRequest();
            inValue.id = id;
            inValue.status = status;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).changeUserStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.AdministradorWS.getUsersByStatusResponse PUCPSaludable.AdministradorWS.AdministradorService.getUsersByStatus(PUCPSaludable.AdministradorWS.getUsersByStatusRequest request) {
            return base.Channel.getUsersByStatus(request);
        }
        
        public PUCPSaludable.AdministradorWS.usuario[] getUsersByStatus(string name, int status) {
            PUCPSaludable.AdministradorWS.getUsersByStatusRequest inValue = new PUCPSaludable.AdministradorWS.getUsersByStatusRequest();
            inValue.name = name;
            inValue.status = status;
            PUCPSaludable.AdministradorWS.getUsersByStatusResponse retVal = ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).getUsersByStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getUsersByStatusResponse> PUCPSaludable.AdministradorWS.AdministradorService.getUsersByStatusAsync(PUCPSaludable.AdministradorWS.getUsersByStatusRequest request) {
            return base.Channel.getUsersByStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.AdministradorWS.getUsersByStatusResponse> getUsersByStatusAsync(string name, int status) {
            PUCPSaludable.AdministradorWS.getUsersByStatusRequest inValue = new PUCPSaludable.AdministradorWS.getUsersByStatusRequest();
            inValue.name = name;
            inValue.status = status;
            return ((PUCPSaludable.AdministradorWS.AdministradorService)(this)).getUsersByStatusAsync(inValue);
        }
    }
}
