//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.IndicadorAntropometricoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="IndicadorAntropometricoWS.IndicadorAntropoService")]
    public interface IndicadorAntropoService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/insertarIndicad" +
            "orAntropomRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/insertarIndicad" +
            "orAntropomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomResponse insertarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/insertarIndicad" +
            "orAntropomRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/insertarIndicad" +
            "orAntropomResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomResponse> insertarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/eliminarIndicad" +
            "orAntropomRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/eliminarIndicad" +
            "orAntropomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomResponse eliminarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/eliminarIndicad" +
            "orAntropomRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/eliminarIndicad" +
            "orAntropomResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomResponse> eliminarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/listarIndicador" +
            "AntropomPorAlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/listarIndicador" +
            "AntropomPorAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoResponse listarIndicadorAntropomPorAlumno(PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/listarIndicador" +
            "AntropomPorAlumnoRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/listarIndicador" +
            "AntropomPorAlumnoResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoResponse> listarIndicadorAntropomPorAlumnoAsync(PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/modificarIndica" +
            "dorAntropomRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/modificarIndica" +
            "dorAntropomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomResponse modificarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/modificarIndica" +
            "dorAntropomRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IndicadorAntropoService/modificarIndica" +
            "dorAntropomResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomResponse> modificarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class indicadorAntropometrico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double circunferenciaAbdominalField;
        
        private double circunferenciaBrazoField;
        
        private double circunferenciaCaderaField;
        
        private double circunferenciaCinturaField;
        
        private double estaturaField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int fid_alumnoField;
        
        private int id_indicadorAntropometricoField;
        
        private double pesoHabitualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double circunferenciaAbdominal {
            get {
                return this.circunferenciaAbdominalField;
            }
            set {
                this.circunferenciaAbdominalField = value;
                this.RaisePropertyChanged("circunferenciaAbdominal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double circunferenciaBrazo {
            get {
                return this.circunferenciaBrazoField;
            }
            set {
                this.circunferenciaBrazoField = value;
                this.RaisePropertyChanged("circunferenciaBrazo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double circunferenciaCadera {
            get {
                return this.circunferenciaCaderaField;
            }
            set {
                this.circunferenciaCaderaField = value;
                this.RaisePropertyChanged("circunferenciaCadera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double circunferenciaCintura {
            get {
                return this.circunferenciaCinturaField;
            }
            set {
                this.circunferenciaCinturaField = value;
                this.RaisePropertyChanged("circunferenciaCintura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double estatura {
            get {
                return this.estaturaField;
            }
            set {
                this.estaturaField = value;
                this.RaisePropertyChanged("estatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int fid_alumno {
            get {
                return this.fid_alumnoField;
            }
            set {
                this.fid_alumnoField = value;
                this.RaisePropertyChanged("fid_alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int id_indicadorAntropometrico {
            get {
                return this.id_indicadorAntropometricoField;
            }
            set {
                this.id_indicadorAntropometricoField = value;
                this.RaisePropertyChanged("id_indicadorAntropometrico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double pesoHabitual {
            get {
                return this.pesoHabitualField;
            }
            set {
                this.pesoHabitualField = value;
                this.RaisePropertyChanged("pesoHabitual");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIndicadorAntropom", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarIndicadorAntropomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico;
        
        public insertarIndicadorAntropomRequest() {
        }
        
        public insertarIndicadorAntropomRequest(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico) {
            this.indicadorAntropometrico = indicadorAntropometrico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIndicadorAntropomResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarIndicadorAntropomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarIndicadorAntropomResponse() {
        }
        
        public insertarIndicadorAntropomResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarIndicadorAntropom", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarIndicadorAntropomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idIndicador;
        
        public eliminarIndicadorAntropomRequest() {
        }
        
        public eliminarIndicadorAntropomRequest(int idIndicador) {
            this.idIndicador = idIndicador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarIndicadorAntropomResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarIndicadorAntropomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarIndicadorAntropomResponse() {
        }
        
        public eliminarIndicadorAntropomResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIndicadorAntropomPorAlumno", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIndicadorAntropomPorAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarIndicadorAntropomPorAlumnoRequest() {
        }
        
        public listarIndicadorAntropomPorAlumnoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIndicadorAntropomPorAlumnoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIndicadorAntropomPorAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico[] @return;
        
        public listarIndicadorAntropomPorAlumnoResponse() {
        }
        
        public listarIndicadorAntropomPorAlumnoResponse(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIndicadorAntropom", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarIndicadorAntropomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico;
        
        public modificarIndicadorAntropomRequest() {
        }
        
        public modificarIndicadorAntropomRequest(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico) {
            this.indicadorAntropometrico = indicadorAntropometrico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIndicadorAntropomResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarIndicadorAntropomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarIndicadorAntropomResponse() {
        }
        
        public modificarIndicadorAntropomResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndicadorAntropoServiceChannel : PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndicadorAntropoServiceClient : System.ServiceModel.ClientBase<PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService>, PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService {
        
        public IndicadorAntropoServiceClient() {
        }
        
        public IndicadorAntropoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndicadorAntropoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndicadorAntropoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndicadorAntropoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomResponse PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.insertarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest request) {
            return base.Channel.insertarIndicadorAntropom(request);
        }
        
        public int insertarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico) {
            PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest();
            inValue.indicadorAntropometrico = indicadorAntropometrico;
            PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomResponse retVal = ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).insertarIndicadorAntropom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomResponse> PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.insertarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest request) {
            return base.Channel.insertarIndicadorAntropomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomResponse> insertarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico) {
            PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.insertarIndicadorAntropomRequest();
            inValue.indicadorAntropometrico = indicadorAntropometrico;
            return ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).insertarIndicadorAntropomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomResponse PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.eliminarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest request) {
            return base.Channel.eliminarIndicadorAntropom(request);
        }
        
        public int eliminarIndicadorAntropom(int idIndicador) {
            PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest();
            inValue.idIndicador = idIndicador;
            PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomResponse retVal = ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).eliminarIndicadorAntropom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomResponse> PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.eliminarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest request) {
            return base.Channel.eliminarIndicadorAntropomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomResponse> eliminarIndicadorAntropomAsync(int idIndicador) {
            PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.eliminarIndicadorAntropomRequest();
            inValue.idIndicador = idIndicador;
            return ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).eliminarIndicadorAntropomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoResponse PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.listarIndicadorAntropomPorAlumno(PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest request) {
            return base.Channel.listarIndicadorAntropomPorAlumno(request);
        }
        
        public PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico[] listarIndicadorAntropomPorAlumno(int id) {
            PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest();
            inValue.id = id;
            PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoResponse retVal = ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).listarIndicadorAntropomPorAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoResponse> PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.listarIndicadorAntropomPorAlumnoAsync(PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest request) {
            return base.Channel.listarIndicadorAntropomPorAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoResponse> listarIndicadorAntropomPorAlumnoAsync(int id) {
            PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.listarIndicadorAntropomPorAlumnoRequest();
            inValue.id = id;
            return ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).listarIndicadorAntropomPorAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomResponse PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.modificarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest request) {
            return base.Channel.modificarIndicadorAntropom(request);
        }
        
        public int modificarIndicadorAntropom(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico) {
            PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest();
            inValue.indicadorAntropometrico = indicadorAntropometrico;
            PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomResponse retVal = ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).modificarIndicadorAntropom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomResponse> PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService.modificarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest request) {
            return base.Channel.modificarIndicadorAntropomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomResponse> modificarIndicadorAntropomAsync(PUCPSaludable.IndicadorAntropometricoWS.indicadorAntropometrico indicadorAntropometrico) {
            PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest inValue = new PUCPSaludable.IndicadorAntropometricoWS.modificarIndicadorAntropomRequest();
            inValue.indicadorAntropometrico = indicadorAntropometrico;
            return ((PUCPSaludable.IndicadorAntropometricoWS.IndicadorAntropoService)(this)).modificarIndicadorAntropomAsync(inValue);
        }
    }
}
