//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.IngredienteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="IngredienteWS.IngredienteService")]
    public interface IngredienteService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "ClasificadosRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "ClasificadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosResponse listarIngredientesNoClasificados(PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "ClasificadosRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "ClasificadosResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosResponse> listarIngredientesNoClasificadosAsync(PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "mbreRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "mbreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.listarIngredientesNombreResponse listarIngredientesNombre(PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "mbreRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesNo" +
            "mbreResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesNombreResponse> listarIngredientesNombreAsync(PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "esetRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "esetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.listarIngredientesPresetResponse listarIngredientesPreset(PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "esetRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "esetResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesPresetResponse> listarIngredientesPresetAsync(PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesTo" +
            "dosRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesTo" +
            "dosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.listarIngredientesTodosResponse listarIngredientesTodos(PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesTo" +
            "dosRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesTo" +
            "dosResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesTodosResponse> listarIngredientesTodosAsync(PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "efAlRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "efAlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.listarIngredientesPrefAlResponse listarIngredientesPrefAl(PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "efAlRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/listarIngredientesPr" +
            "efAlResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesPrefAlResponse> listarIngredientesPrefAlAsync(PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/eliminarIngreRequest" +
            "", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/eliminarIngreRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.eliminarIngreResponse eliminarIngre(PUCPSaludable.IngredienteWS.eliminarIngreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/eliminarIngreRequest" +
            "", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/eliminarIngreRespons" +
            "e")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.eliminarIngreResponse> eliminarIngreAsync(PUCPSaludable.IngredienteWS.eliminarIngreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/modificarIngreReques" +
            "t", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/modificarIngreRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.modificarIngreResponse modificarIngre(PUCPSaludable.IngredienteWS.modificarIngreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/modificarIngreReques" +
            "t", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/modificarIngreRespon" +
            "se")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.modificarIngreResponse> modificarIngreAsync(PUCPSaludable.IngredienteWS.modificarIngreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/insertarIngreRequest" +
            "", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/insertarIngreRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.IngredienteWS.insertarIngreResponse insertarIngre(PUCPSaludable.IngredienteWS.insertarIngreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/insertarIngreRequest" +
            "", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/IngredienteService/insertarIngreRespons" +
            "e")]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.insertarIngreResponse> insertarIngreAsync(PUCPSaludable.IngredienteWS.insertarIngreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class ingrediente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool azucarField;
        
        private double cantidadField;
        
        private string detalleField;
        
        private bool estadoField;
        
        private bool grasasSaturadasField;
        
        private bool grasasTransField;
        
        private int idIngredienteField;
        
        private int kcalField;
        
        private string nombreField;
        
        private bool sodioField;
        
        private string unidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool azucar {
            get {
                return this.azucarField;
            }
            set {
                this.azucarField = value;
                this.RaisePropertyChanged("azucar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool grasasSaturadas {
            get {
                return this.grasasSaturadasField;
            }
            set {
                this.grasasSaturadasField = value;
                this.RaisePropertyChanged("grasasSaturadas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool grasasTrans {
            get {
                return this.grasasTransField;
            }
            set {
                this.grasasTransField = value;
                this.RaisePropertyChanged("grasasTrans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idIngrediente {
            get {
                return this.idIngredienteField;
            }
            set {
                this.idIngredienteField = value;
                this.RaisePropertyChanged("idIngrediente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int kcal {
            get {
                return this.kcalField;
            }
            set {
                this.kcalField = value;
                this.RaisePropertyChanged("kcal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool sodio {
            get {
                return this.sodioField;
            }
            set {
                this.sodioField = value;
                this.RaisePropertyChanged("sodio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
                this.RaisePropertyChanged("unidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesNoClasificados", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesNoClasificadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        public listarIngredientesNoClasificadosRequest() {
        }
        
        public listarIngredientesNoClasificadosRequest(int idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesNoClasificadosResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesNoClasificadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente[] @return;
        
        public listarIngredientesNoClasificadosResponse() {
        }
        
        public listarIngredientesNoClasificadosResponse(PUCPSaludable.IngredienteWS.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesNombre", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarIngredientesNombreRequest() {
        }
        
        public listarIngredientesNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesNombreResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente[] @return;
        
        public listarIngredientesNombreResponse() {
        }
        
        public listarIngredientesNombreResponse(PUCPSaludable.IngredienteWS.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesPreset", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesPresetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPreset;
        
        public listarIngredientesPresetRequest() {
        }
        
        public listarIngredientesPresetRequest(int idPreset) {
            this.idPreset = idPreset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesPresetResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesPresetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente[] @return;
        
        public listarIngredientesPresetResponse() {
        }
        
        public listarIngredientesPresetResponse(PUCPSaludable.IngredienteWS.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesTodos", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesTodosRequest {
        
        public listarIngredientesTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesTodosResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente[] @return;
        
        public listarIngredientesTodosResponse() {
        }
        
        public listarIngredientesTodosResponse(PUCPSaludable.IngredienteWS.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesPrefAl", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesPrefAlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlumno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int preferencia;
        
        public listarIngredientesPrefAlRequest() {
        }
        
        public listarIngredientesPrefAlRequest(int idAlumno, int preferencia) {
            this.idAlumno = idAlumno;
            this.preferencia = preferencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesPrefAlResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngredientesPrefAlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente[] @return;
        
        public listarIngredientesPrefAlResponse() {
        }
        
        public listarIngredientesPrefAlResponse(PUCPSaludable.IngredienteWS.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarIngre", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarIngreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente ingred;
        
        public eliminarIngreRequest() {
        }
        
        public eliminarIngreRequest(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            this.ingred = ingred;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarIngreResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarIngreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarIngreResponse() {
        }
        
        public eliminarIngreResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIngre", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarIngreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente ingred;
        
        public modificarIngreRequest() {
        }
        
        public modificarIngreRequest(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            this.ingred = ingred;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIngreResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarIngreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarIngreResponse() {
        }
        
        public modificarIngreResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIngre", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarIngreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.IngredienteWS.ingrediente ingred;
        
        public insertarIngreRequest() {
        }
        
        public insertarIngreRequest(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            this.ingred = ingred;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIngreResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarIngreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarIngreResponse() {
        }
        
        public insertarIngreResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngredienteServiceChannel : PUCPSaludable.IngredienteWS.IngredienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngredienteServiceClient : System.ServiceModel.ClientBase<PUCPSaludable.IngredienteWS.IngredienteService>, PUCPSaludable.IngredienteWS.IngredienteService {
        
        public IngredienteServiceClient() {
        }
        
        public IngredienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngredienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngredienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngredienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosResponse PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesNoClasificados(PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest request) {
            return base.Channel.listarIngredientesNoClasificados(request);
        }
        
        public PUCPSaludable.IngredienteWS.ingrediente[] listarIngredientesNoClasificados(int idAlumno) {
            PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest();
            inValue.idAlumno = idAlumno;
            PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesNoClasificados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosResponse> PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesNoClasificadosAsync(PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest request) {
            return base.Channel.listarIngredientesNoClasificadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosResponse> listarIngredientesNoClasificadosAsync(int idAlumno) {
            PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesNoClasificadosRequest();
            inValue.idAlumno = idAlumno;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesNoClasificadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.listarIngredientesNombreResponse PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesNombre(PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest request) {
            return base.Channel.listarIngredientesNombre(request);
        }
        
        public PUCPSaludable.IngredienteWS.ingrediente[] listarIngredientesNombre(string nombre) {
            PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest();
            inValue.nombre = nombre;
            PUCPSaludable.IngredienteWS.listarIngredientesNombreResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesNombreResponse> PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesNombreAsync(PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest request) {
            return base.Channel.listarIngredientesNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesNombreResponse> listarIngredientesNombreAsync(string nombre) {
            PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesNombreRequest();
            inValue.nombre = nombre;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.listarIngredientesPresetResponse PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesPreset(PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest request) {
            return base.Channel.listarIngredientesPreset(request);
        }
        
        public PUCPSaludable.IngredienteWS.ingrediente[] listarIngredientesPreset(int idPreset) {
            PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest();
            inValue.idPreset = idPreset;
            PUCPSaludable.IngredienteWS.listarIngredientesPresetResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesPreset(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesPresetResponse> PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesPresetAsync(PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest request) {
            return base.Channel.listarIngredientesPresetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesPresetResponse> listarIngredientesPresetAsync(int idPreset) {
            PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesPresetRequest();
            inValue.idPreset = idPreset;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesPresetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.listarIngredientesTodosResponse PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesTodos(PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest request) {
            return base.Channel.listarIngredientesTodos(request);
        }
        
        public PUCPSaludable.IngredienteWS.ingrediente[] listarIngredientesTodos() {
            PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest();
            PUCPSaludable.IngredienteWS.listarIngredientesTodosResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesTodosResponse> PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesTodosAsync(PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest request) {
            return base.Channel.listarIngredientesTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesTodosResponse> listarIngredientesTodosAsync() {
            PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesTodosRequest();
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.listarIngredientesPrefAlResponse PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesPrefAl(PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest request) {
            return base.Channel.listarIngredientesPrefAl(request);
        }
        
        public PUCPSaludable.IngredienteWS.ingrediente[] listarIngredientesPrefAl(int idAlumno, int preferencia) {
            PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest();
            inValue.idAlumno = idAlumno;
            inValue.preferencia = preferencia;
            PUCPSaludable.IngredienteWS.listarIngredientesPrefAlResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesPrefAl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesPrefAlResponse> PUCPSaludable.IngredienteWS.IngredienteService.listarIngredientesPrefAlAsync(PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest request) {
            return base.Channel.listarIngredientesPrefAlAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.listarIngredientesPrefAlResponse> listarIngredientesPrefAlAsync(int idAlumno, int preferencia) {
            PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest inValue = new PUCPSaludable.IngredienteWS.listarIngredientesPrefAlRequest();
            inValue.idAlumno = idAlumno;
            inValue.preferencia = preferencia;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).listarIngredientesPrefAlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.eliminarIngreResponse PUCPSaludable.IngredienteWS.IngredienteService.eliminarIngre(PUCPSaludable.IngredienteWS.eliminarIngreRequest request) {
            return base.Channel.eliminarIngre(request);
        }
        
        public int eliminarIngre(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            PUCPSaludable.IngredienteWS.eliminarIngreRequest inValue = new PUCPSaludable.IngredienteWS.eliminarIngreRequest();
            inValue.ingred = ingred;
            PUCPSaludable.IngredienteWS.eliminarIngreResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).eliminarIngre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.eliminarIngreResponse> PUCPSaludable.IngredienteWS.IngredienteService.eliminarIngreAsync(PUCPSaludable.IngredienteWS.eliminarIngreRequest request) {
            return base.Channel.eliminarIngreAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.eliminarIngreResponse> eliminarIngreAsync(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            PUCPSaludable.IngredienteWS.eliminarIngreRequest inValue = new PUCPSaludable.IngredienteWS.eliminarIngreRequest();
            inValue.ingred = ingred;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).eliminarIngreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.modificarIngreResponse PUCPSaludable.IngredienteWS.IngredienteService.modificarIngre(PUCPSaludable.IngredienteWS.modificarIngreRequest request) {
            return base.Channel.modificarIngre(request);
        }
        
        public int modificarIngre(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            PUCPSaludable.IngredienteWS.modificarIngreRequest inValue = new PUCPSaludable.IngredienteWS.modificarIngreRequest();
            inValue.ingred = ingred;
            PUCPSaludable.IngredienteWS.modificarIngreResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).modificarIngre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.modificarIngreResponse> PUCPSaludable.IngredienteWS.IngredienteService.modificarIngreAsync(PUCPSaludable.IngredienteWS.modificarIngreRequest request) {
            return base.Channel.modificarIngreAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.modificarIngreResponse> modificarIngreAsync(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            PUCPSaludable.IngredienteWS.modificarIngreRequest inValue = new PUCPSaludable.IngredienteWS.modificarIngreRequest();
            inValue.ingred = ingred;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).modificarIngreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.IngredienteWS.insertarIngreResponse PUCPSaludable.IngredienteWS.IngredienteService.insertarIngre(PUCPSaludable.IngredienteWS.insertarIngreRequest request) {
            return base.Channel.insertarIngre(request);
        }
        
        public int insertarIngre(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            PUCPSaludable.IngredienteWS.insertarIngreRequest inValue = new PUCPSaludable.IngredienteWS.insertarIngreRequest();
            inValue.ingred = ingred;
            PUCPSaludable.IngredienteWS.insertarIngreResponse retVal = ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).insertarIngre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.insertarIngreResponse> PUCPSaludable.IngredienteWS.IngredienteService.insertarIngreAsync(PUCPSaludable.IngredienteWS.insertarIngreRequest request) {
            return base.Channel.insertarIngreAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.IngredienteWS.insertarIngreResponse> insertarIngreAsync(PUCPSaludable.IngredienteWS.ingrediente ingred) {
            PUCPSaludable.IngredienteWS.insertarIngreRequest inValue = new PUCPSaludable.IngredienteWS.insertarIngreRequest();
            inValue.ingred = ingred;
            return ((PUCPSaludable.IngredienteWS.IngredienteService)(this)).insertarIngreAsync(inValue);
        }
    }
}
