//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.HorasSuenhoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="HorasSuenhoWS.HorasSuenhoServices")]
    public interface HorasSuenhoServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/eliminarHorasSuenho" +
            "Request", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/eliminarHorasSuenho" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoResponse eliminarHorasSuenho(PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/eliminarHorasSuenho" +
            "Request", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/eliminarHorasSuenho" +
            "Response")]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoResponse> eliminarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/modificarHorasSuenh" +
            "oRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/modificarHorasSuenh" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoResponse modificarHorasSuenho(PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/modificarHorasSuenh" +
            "oRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/modificarHorasSuenh" +
            "oResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoResponse> modificarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/insertarHorasSuenho" +
            "Request", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/insertarHorasSuenho" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoResponse insertarHorasSuenho(PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/insertarHorasSuenho" +
            "Request", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/insertarHorasSuenho" +
            "Response")]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoResponse> insertarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/listarHorasSuenPorA" +
            "lumRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/listarHorasSuenPorA" +
            "lumResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumResponse listarHorasSuenPorAlum(PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/listarHorasSuenPorA" +
            "lumRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorasSuenhoServices/listarHorasSuenPorA" +
            "lumResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumResponse> listarHorasSuenPorAlumAsync(PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarHorasSuenho", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarHorasSuenhoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idHorasSue;
        
        public eliminarHorasSuenhoRequest() {
        }
        
        public eliminarHorasSuenhoRequest(int idHorasSue) {
            this.idHorasSue = idHorasSue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarHorasSuenhoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarHorasSuenhoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarHorasSuenhoResponse() {
        }
        
        public eliminarHorasSuenhoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class horasSuenho : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int fid_alumnoField;
        
        private double horasField;
        
        private int id_horasSuenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int fid_alumno {
            get {
                return this.fid_alumnoField;
            }
            set {
                this.fid_alumnoField = value;
                this.RaisePropertyChanged("fid_alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double horas {
            get {
                return this.horasField;
            }
            set {
                this.horasField = value;
                this.RaisePropertyChanged("horas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_horasSueno {
            get {
                return this.id_horasSuenoField;
            }
            set {
                this.id_horasSuenoField = value;
                this.RaisePropertyChanged("id_horasSueno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHorasSuenho", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarHorasSuenhoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue;
        
        public modificarHorasSuenhoRequest() {
        }
        
        public modificarHorasSuenhoRequest(PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue) {
            this.horasSue = horasSue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHorasSuenhoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarHorasSuenhoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarHorasSuenhoResponse() {
        }
        
        public modificarHorasSuenhoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarHorasSuenho", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarHorasSuenhoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue;
        
        public insertarHorasSuenhoRequest() {
        }
        
        public insertarHorasSuenhoRequest(PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue) {
            this.horasSue = horasSue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarHorasSuenhoResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarHorasSuenhoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarHorasSuenhoResponse() {
        }
        
        public insertarHorasSuenhoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHorasSuenPorAlum", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarHorasSuenPorAlumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAl;
        
        public listarHorasSuenPorAlumRequest() {
        }
        
        public listarHorasSuenPorAlumRequest(int idAl) {
            this.idAl = idAl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarHorasSuenPorAlumResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarHorasSuenPorAlumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.HorasSuenhoWS.horasSuenho[] @return;
        
        public listarHorasSuenPorAlumResponse() {
        }
        
        public listarHorasSuenPorAlumResponse(PUCPSaludable.HorasSuenhoWS.horasSuenho[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HorasSuenhoServicesChannel : PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorasSuenhoServicesClient : System.ServiceModel.ClientBase<PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices>, PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices {
        
        public HorasSuenhoServicesClient() {
        }
        
        public HorasSuenhoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorasSuenhoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorasSuenhoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorasSuenhoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoResponse PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.eliminarHorasSuenho(PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest request) {
            return base.Channel.eliminarHorasSuenho(request);
        }
        
        public int eliminarHorasSuenho(int idHorasSue) {
            PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest inValue = new PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest();
            inValue.idHorasSue = idHorasSue;
            PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoResponse retVal = ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).eliminarHorasSuenho(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoResponse> PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.eliminarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest request) {
            return base.Channel.eliminarHorasSuenhoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoResponse> eliminarHorasSuenhoAsync(int idHorasSue) {
            PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest inValue = new PUCPSaludable.HorasSuenhoWS.eliminarHorasSuenhoRequest();
            inValue.idHorasSue = idHorasSue;
            return ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).eliminarHorasSuenhoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoResponse PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.modificarHorasSuenho(PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest request) {
            return base.Channel.modificarHorasSuenho(request);
        }
        
        public int modificarHorasSuenho(PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue) {
            PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest inValue = new PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest();
            inValue.horasSue = horasSue;
            PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoResponse retVal = ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).modificarHorasSuenho(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoResponse> PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.modificarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest request) {
            return base.Channel.modificarHorasSuenhoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoResponse> modificarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue) {
            PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest inValue = new PUCPSaludable.HorasSuenhoWS.modificarHorasSuenhoRequest();
            inValue.horasSue = horasSue;
            return ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).modificarHorasSuenhoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoResponse PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.insertarHorasSuenho(PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest request) {
            return base.Channel.insertarHorasSuenho(request);
        }
        
        public int insertarHorasSuenho(PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue) {
            PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest inValue = new PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest();
            inValue.horasSue = horasSue;
            PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoResponse retVal = ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).insertarHorasSuenho(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoResponse> PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.insertarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest request) {
            return base.Channel.insertarHorasSuenhoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoResponse> insertarHorasSuenhoAsync(PUCPSaludable.HorasSuenhoWS.horasSuenho horasSue) {
            PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest inValue = new PUCPSaludable.HorasSuenhoWS.insertarHorasSuenhoRequest();
            inValue.horasSue = horasSue;
            return ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).insertarHorasSuenhoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumResponse PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.listarHorasSuenPorAlum(PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest request) {
            return base.Channel.listarHorasSuenPorAlum(request);
        }
        
        public PUCPSaludable.HorasSuenhoWS.horasSuenho[] listarHorasSuenPorAlum(int idAl) {
            PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest inValue = new PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest();
            inValue.idAl = idAl;
            PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumResponse retVal = ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).listarHorasSuenPorAlum(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumResponse> PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices.listarHorasSuenPorAlumAsync(PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest request) {
            return base.Channel.listarHorasSuenPorAlumAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumResponse> listarHorasSuenPorAlumAsync(int idAl) {
            PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest inValue = new PUCPSaludable.HorasSuenhoWS.listarHorasSuenPorAlumRequest();
            inValue.idAl = idAl;
            return ((PUCPSaludable.HorasSuenhoWS.HorasSuenhoServices)(this)).listarHorasSuenPorAlumAsync(inValue);
        }
    }
}
