//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUCPSaludable.HorarioHabitualWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", ConfigurationName="HorarioHabitualWS.HorarioHabitualService")]
    public interface HorarioHabitualService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/obtenerHorarioHa" +
            "bitualRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/obtenerHorarioHa" +
            "bitualResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualResponse obtenerHorarioHabitual(PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/obtenerHorarioHa" +
            "bitualRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/obtenerHorarioHa" +
            "bitualResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualResponse> obtenerHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/modificarHorario" +
            "HabitualRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/modificarHorario" +
            "HabitualResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualResponse modificarHorarioHabitual(PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/modificarHorario" +
            "HabitualRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/modificarHorario" +
            "HabitualResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualResponse> modificarHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/insertarHorarioH" +
            "abitualRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/insertarHorarioH" +
            "abitualResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualResponse insertarHorarioHabitual(PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/insertarHorarioH" +
            "abitualRequest", ReplyAction="http://services.pucpsaludable.pucp.edu.pe/HorarioHabitualService/insertarHorarioH" +
            "abitualResponse")]
        System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualResponse> insertarHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/")]
    public partial class horarioHabitual : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime acostarseField;
        
        private bool acostarseFieldSpecified;
        
        private System.DateTime cenaField;
        
        private bool cenaFieldSpecified;
        
        private System.DateTime comidaField;
        
        private bool comidaFieldSpecified;
        
        private System.DateTime desayunoField;
        
        private bool desayunoFieldSpecified;
        
        private System.DateTime despertarseField;
        
        private bool despertarseFieldSpecified;
        
        private int fid_alumnoField;
        
        private System.DateTime mediaMananaField;
        
        private bool mediaMananaFieldSpecified;
        
        private System.DateTime meriendaField;
        
        private bool meriendaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime acostarse {
            get {
                return this.acostarseField;
            }
            set {
                this.acostarseField = value;
                this.RaisePropertyChanged("acostarse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acostarseSpecified {
            get {
                return this.acostarseFieldSpecified;
            }
            set {
                this.acostarseFieldSpecified = value;
                this.RaisePropertyChanged("acostarseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
                this.RaisePropertyChanged("cena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cenaSpecified {
            get {
                return this.cenaFieldSpecified;
            }
            set {
                this.cenaFieldSpecified = value;
                this.RaisePropertyChanged("cenaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime comida {
            get {
                return this.comidaField;
            }
            set {
                this.comidaField = value;
                this.RaisePropertyChanged("comida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comidaSpecified {
            get {
                return this.comidaFieldSpecified;
            }
            set {
                this.comidaFieldSpecified = value;
                this.RaisePropertyChanged("comidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime desayuno {
            get {
                return this.desayunoField;
            }
            set {
                this.desayunoField = value;
                this.RaisePropertyChanged("desayuno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desayunoSpecified {
            get {
                return this.desayunoFieldSpecified;
            }
            set {
                this.desayunoFieldSpecified = value;
                this.RaisePropertyChanged("desayunoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime despertarse {
            get {
                return this.despertarseField;
            }
            set {
                this.despertarseField = value;
                this.RaisePropertyChanged("despertarse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool despertarseSpecified {
            get {
                return this.despertarseFieldSpecified;
            }
            set {
                this.despertarseFieldSpecified = value;
                this.RaisePropertyChanged("despertarseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int fid_alumno {
            get {
                return this.fid_alumnoField;
            }
            set {
                this.fid_alumnoField = value;
                this.RaisePropertyChanged("fid_alumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime mediaManana {
            get {
                return this.mediaMananaField;
            }
            set {
                this.mediaMananaField = value;
                this.RaisePropertyChanged("mediaManana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mediaMananaSpecified {
            get {
                return this.mediaMananaFieldSpecified;
            }
            set {
                this.mediaMananaFieldSpecified = value;
                this.RaisePropertyChanged("mediaMananaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime merienda {
            get {
                return this.meriendaField;
            }
            set {
                this.meriendaField = value;
                this.RaisePropertyChanged("merienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meriendaSpecified {
            get {
                return this.meriendaFieldSpecified;
            }
            set {
                this.meriendaFieldSpecified = value;
                this.RaisePropertyChanged("meriendaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerHorarioHabitual", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerHorarioHabitualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_alumno;
        
        public obtenerHorarioHabitualRequest() {
        }
        
        public obtenerHorarioHabitualRequest(int id_alumno) {
            this.id_alumno = id_alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerHorarioHabitualResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerHorarioHabitualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.HorarioHabitualWS.horarioHabitual @return;
        
        public obtenerHorarioHabitualResponse() {
        }
        
        public obtenerHorarioHabitualResponse(PUCPSaludable.HorarioHabitualWS.horarioHabitual @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHorarioHabitual", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarHorarioHabitualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab;
        
        public modificarHorarioHabitualRequest() {
        }
        
        public modificarHorarioHabitualRequest(PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab) {
            this.horarioHab = horarioHab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarHorarioHabitualResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarHorarioHabitualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarHorarioHabitualResponse() {
        }
        
        public modificarHorarioHabitualResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarHorarioHabitual", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarHorarioHabitualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab;
        
        public insertarHorarioHabitualRequest() {
        }
        
        public insertarHorarioHabitualRequest(PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab) {
            this.horarioHab = horarioHab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarHorarioHabitualResponse", WrapperNamespace="http://services.pucpsaludable.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarHorarioHabitualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.pucpsaludable.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarHorarioHabitualResponse() {
        }
        
        public insertarHorarioHabitualResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HorarioHabitualServiceChannel : PUCPSaludable.HorarioHabitualWS.HorarioHabitualService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorarioHabitualServiceClient : System.ServiceModel.ClientBase<PUCPSaludable.HorarioHabitualWS.HorarioHabitualService>, PUCPSaludable.HorarioHabitualWS.HorarioHabitualService {
        
        public HorarioHabitualServiceClient() {
        }
        
        public HorarioHabitualServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorarioHabitualServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioHabitualServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioHabitualServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualResponse PUCPSaludable.HorarioHabitualWS.HorarioHabitualService.obtenerHorarioHabitual(PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest request) {
            return base.Channel.obtenerHorarioHabitual(request);
        }
        
        public PUCPSaludable.HorarioHabitualWS.horarioHabitual obtenerHorarioHabitual(int id_alumno) {
            PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest inValue = new PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest();
            inValue.id_alumno = id_alumno;
            PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualResponse retVal = ((PUCPSaludable.HorarioHabitualWS.HorarioHabitualService)(this)).obtenerHorarioHabitual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualResponse> PUCPSaludable.HorarioHabitualWS.HorarioHabitualService.obtenerHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest request) {
            return base.Channel.obtenerHorarioHabitualAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualResponse> obtenerHorarioHabitualAsync(int id_alumno) {
            PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest inValue = new PUCPSaludable.HorarioHabitualWS.obtenerHorarioHabitualRequest();
            inValue.id_alumno = id_alumno;
            return ((PUCPSaludable.HorarioHabitualWS.HorarioHabitualService)(this)).obtenerHorarioHabitualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualResponse PUCPSaludable.HorarioHabitualWS.HorarioHabitualService.modificarHorarioHabitual(PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest request) {
            return base.Channel.modificarHorarioHabitual(request);
        }
        
        public int modificarHorarioHabitual(PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab) {
            PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest inValue = new PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest();
            inValue.horarioHab = horarioHab;
            PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualResponse retVal = ((PUCPSaludable.HorarioHabitualWS.HorarioHabitualService)(this)).modificarHorarioHabitual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualResponse> PUCPSaludable.HorarioHabitualWS.HorarioHabitualService.modificarHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest request) {
            return base.Channel.modificarHorarioHabitualAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualResponse> modificarHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab) {
            PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest inValue = new PUCPSaludable.HorarioHabitualWS.modificarHorarioHabitualRequest();
            inValue.horarioHab = horarioHab;
            return ((PUCPSaludable.HorarioHabitualWS.HorarioHabitualService)(this)).modificarHorarioHabitualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualResponse PUCPSaludable.HorarioHabitualWS.HorarioHabitualService.insertarHorarioHabitual(PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest request) {
            return base.Channel.insertarHorarioHabitual(request);
        }
        
        public int insertarHorarioHabitual(PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab) {
            PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest inValue = new PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest();
            inValue.horarioHab = horarioHab;
            PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualResponse retVal = ((PUCPSaludable.HorarioHabitualWS.HorarioHabitualService)(this)).insertarHorarioHabitual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualResponse> PUCPSaludable.HorarioHabitualWS.HorarioHabitualService.insertarHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest request) {
            return base.Channel.insertarHorarioHabitualAsync(request);
        }
        
        public System.Threading.Tasks.Task<PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualResponse> insertarHorarioHabitualAsync(PUCPSaludable.HorarioHabitualWS.horarioHabitual horarioHab) {
            PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest inValue = new PUCPSaludable.HorarioHabitualWS.insertarHorarioHabitualRequest();
            inValue.horarioHab = horarioHab;
            return ((PUCPSaludable.HorarioHabitualWS.HorarioHabitualService)(this)).insertarHorarioHabitualAsync(inValue);
        }
    }
}
